#!/bin/bash
#
#  setup_cmake Chooses the correct cmake build command for a machine.
#
#-------------------------------------------------------------------------------

BUILD_TYPE=Release

MACHINE_ID=`uname -n`

echo Building v3fit suite for machine $MACHINE_ID
echo

if [ $# -eq 1 ]
then
    BUILD_TYPE=Debug
fi

echo cmake configured to generate a $BUILD_TYPE build.
if [ "$BUILD_TYPE" == Debug ]
then
    echo "    cmake may be reconfigured to generate a Release build by running this script with no arguments or using the commmand"
    echo
    echo "    cmake -DCMAKE_BUILD_TYPE=Release"
else
    echo "    cmake may be reconfigured to generate a Debug build by running this script with a Debug argument or using the commmand"
    echo
    echo "    cmake -DCMAKE_BUILD_TYPE=Debug"
fi

mkdir -p build
cd build

if   [ $MACHINE_ID == "mbp103254"     ] || \
     [ $MACHINE_ID == "cianciosaimac" ]
then
    # Config for Mark Cianciosa's ORNL machine.
    cmake -DCMAKE_BUILD_TYPE:String=$BUILD_TYPE \
          ../

else
# MACHINE_ID is new and unknown. Inform the user how to add support for this new machine.
    echo $MACHINE_ID not suported by this script.
    echo To support this machine, add a new elif statement of the form
    echo
    echo elif [ \$MACHINE_ID == \"$MACHINE_ID\" ]
    echo then
    echo "   " cmake -DVARIABLE=value ...
    echo
fi
