#!/bin/bash
#
#  setup_cmake Chooses the correct cmake build command for a machine.
#
#-------------------------------------------------------------------------------

BUILD_TYPE=Release

MACHINE_ID=`uname -n`

echo Building stellarator tools for machine $MACHINE_ID
echo

if [ $# -eq 1 ]
then
    BUILD_TYPE=Debug
fi

echo cmake configured to generate a $BUILD_TYPE build.
if [ "$BUILD_TYPE" == Debug ]
then
    echo "    cmake may be reconfigured to generate a Release build by running this script with no arguments or using the commmand"
    echo
    echo "    cmake -DCMAKE_BUILD_TYPE=Release"
else
    echo "    cmake may be reconfigured to generate a Debug build by running this script with a Debug argument or using the commmand"
    echo
    echo "    cmake -DCMAKE_BUILD_TYPE=Debug"
fi

mkdir -p build
cd build

if   [ $MACHINE_ID == "mbp103254"     ] || \
     [ $MACHINE_ID == "cianciosaimac" ]
then
    # Config for Mark Cianciosa's ORNL machine.
    cmake -DCMAKE_BUILD_TYPE:String=$BUILD_TYPE \
          -DBUILD_MAKEGRID=ON                   \
          ../

elif [ $MACHINE_ID == "Nebuchadnezaar" ] || \
     [ $MACHINE_ID == "Z820" ]
then
    # Config for Jonathan Schilling's Arch Linux machines.
    # -fallow-argument-mismatch is needed for GCC-10.
    cmake -DCMAKE_BUILD_TYPE:String=$BUILD_TYPE             \
          -DUSE_SSH=ON                                      \
          -DBUILD_PARVMEC=ON                                \
          -DCMAKE_Fortran_FLAGS="-fallow-argument-mismatch" \
          ../

elif [ $MACHINE_ID == "sv-e5-da-1" ]
then
    # Config for J. Schilling's IPP machine.
    cmake -DCMAKE_BUILD_TYPE:String=$BUILD_TYPE             \
          -DUSE_SSH=ON                                      \
          -DBUILD_PARVMEC=ON                                \
          ../

else
# MACHINE_ID is new and unknown. Inform the user how to add support for this new machine.
    echo $MACHINE_ID not suported by this script.
    echo To support this machine, add a new elif statement of the form
    echo
    echo elif [ \$MACHINE_ID == \"$MACHINE_ID\" ]
    echo then
    echo "   " cmake -DVARIABLE=value ...
    echo
fi
